package com.letsdevlope.models;
// Generated May 19, 2017 3:42:08 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommentId generated by hbm2java
 */
@Embeddable
public class CommentId implements java.io.Serializable {

	private int commentId;
	private int blogBlogId;
	private int userUserId;

	public CommentId() {
	}

	public CommentId(int commentId, int blogBlogId, int userUserId) {
		this.commentId = commentId;
		this.blogBlogId = blogBlogId;
		this.userUserId = userUserId;
	}

	@Column(name = "COMMENT_ID", nullable = false)
	public int getCommentId() {
		return this.commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	@Column(name = "BLOG_BLOG_ID", nullable = false)
	public int getBlogBlogId() {
		return this.blogBlogId;
	}

	public void setBlogBlogId(int blogBlogId) {
		this.blogBlogId = blogBlogId;
	}

	@Column(name = "USER_USER_ID", nullable = false)
	public int getUserUserId() {
		return this.userUserId;
	}

	public void setUserUserId(int userUserId) {
		this.userUserId = userUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentId))
			return false;
		CommentId castOther = (CommentId) other;

		return (this.getCommentId() == castOther.getCommentId()) && (this.getBlogBlogId() == castOther.getBlogBlogId())
				&& (this.getUserUserId() == castOther.getUserUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommentId();
		result = 37 * result + this.getBlogBlogId();
		result = 37 * result + this.getUserUserId();
		return result;
	}

}
