package com.letsdevlope.models;
// Generated May 19, 2017 3:42:08 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag", catalog = "mydb")
public class Tag implements java.io.Serializable {

	private TagId id;
	private Blog blog;
	private String tagName;
	private Date tagCreated;
	private Date tagUpdated;
	private Byte tagIsdeleted;

	public Tag() {
	}

	public Tag(TagId id, Blog blog) {
		this.id = id;
		this.blog = blog;
	}

	public Tag(TagId id, Blog blog, String tagName, Date tagCreated, Date tagUpdated, Byte tagIsdeleted) {
		this.id = id;
		this.blog = blog;
		this.tagName = tagName;
		this.tagCreated = tagCreated;
		this.tagUpdated = tagUpdated;
		this.tagIsdeleted = tagIsdeleted;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "tagId", column = @Column(name = "TAG_ID", nullable = false)),
			@AttributeOverride(name = "blogBlogId", column = @Column(name = "BLOG_BLOG_ID", nullable = false)) })
	public TagId getId() {
		return this.id;
	}

	public void setId(TagId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BLOG_BLOG_ID", nullable = false, insertable = false, updatable = false)
	public Blog getBlog() {
		return this.blog;
	}

	public void setBlog(Blog blog) {
		this.blog = blog;
	}

	@Column(name = "TAG_NAME", length = 45)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TAG_CREATED", length = 19)
	public Date getTagCreated() {
		return this.tagCreated;
	}

	public void setTagCreated(Date tagCreated) {
		this.tagCreated = tagCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TAG_UPDATED", length = 19)
	public Date getTagUpdated() {
		return this.tagUpdated;
	}

	public void setTagUpdated(Date tagUpdated) {
		this.tagUpdated = tagUpdated;
	}

	@Column(name = "TAG_ISDELETED")
	public Byte getTagIsdeleted() {
		return this.tagIsdeleted;
	}

	public void setTagIsdeleted(Byte tagIsdeleted) {
		this.tagIsdeleted = tagIsdeleted;
	}

}
