package reverseengineeringmysql.mysqlreveng;
// Generated May 19, 2017 3:42:08 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "mydb")
public class Comment implements java.io.Serializable {

	private CommentId id;
	private Blog blog;
	private User user;
	private String comment;
	private Date commentCreated;
	private Date commentUpdated;

	public Comment() {
	}

	public Comment(CommentId id, Blog blog, User user) {
		this.id = id;
		this.blog = blog;
		this.user = user;
	}

	public Comment(CommentId id, Blog blog, User user, String comment, Date commentCreated, Date commentUpdated) {
		this.id = id;
		this.blog = blog;
		this.user = user;
		this.comment = comment;
		this.commentCreated = commentCreated;
		this.commentUpdated = commentUpdated;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "commentId", column = @Column(name = "COMMENT_ID", nullable = false)),
			@AttributeOverride(name = "blogBlogId", column = @Column(name = "BLOG_BLOG_ID", nullable = false)),
			@AttributeOverride(name = "userUserId", column = @Column(name = "USER_USER_ID", nullable = false)) })
	public CommentId getId() {
		return this.id;
	}

	public void setId(CommentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BLOG_BLOG_ID", nullable = false, insertable = false, updatable = false)
	public Blog getBlog() {
		return this.blog;
	}

	public void setBlog(Blog blog) {
		this.blog = blog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_USER_ID", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "COMMENT")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMMENT_CREATED", length = 19)
	public Date getCommentCreated() {
		return this.commentCreated;
	}

	public void setCommentCreated(Date commentCreated) {
		this.commentCreated = commentCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMMENT_UPDATED", length = 19)
	public Date getCommentUpdated() {
		return this.commentUpdated;
	}

	public void setCommentUpdated(Date commentUpdated) {
		this.commentUpdated = commentUpdated;
	}

}
