package reverseengineeringmysql.mysqlreveng;
// Generated May 19, 2017 3:42:08 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SkillId generated by hbm2java
 */
@Embeddable
public class SkillId implements java.io.Serializable {

	private int skillId;
	private int userUserId;

	public SkillId() {
	}

	public SkillId(int skillId, int userUserId) {
		this.skillId = skillId;
		this.userUserId = userUserId;
	}

	@Column(name = "SKILL_ID", nullable = false)
	public int getSkillId() {
		return this.skillId;
	}

	public void setSkillId(int skillId) {
		this.skillId = skillId;
	}

	@Column(name = "USER_USER_ID", nullable = false)
	public int getUserUserId() {
		return this.userUserId;
	}

	public void setUserUserId(int userUserId) {
		this.userUserId = userUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SkillId))
			return false;
		SkillId castOther = (SkillId) other;

		return (this.getSkillId() == castOther.getSkillId()) && (this.getUserUserId() == castOther.getUserUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSkillId();
		result = 37 * result + this.getUserUserId();
		return result;
	}

}
