package reverseengineeringmysql.mysqlreveng;
// Generated May 19, 2017 3:42:08 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TagId generated by hbm2java
 */
@Embeddable
public class TagId implements java.io.Serializable {

	private int tagId;
	private int blogBlogId;

	public TagId() {
	}

	public TagId(int tagId, int blogBlogId) {
		this.tagId = tagId;
		this.blogBlogId = blogBlogId;
	}

	@Column(name = "TAG_ID", nullable = false)
	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	@Column(name = "BLOG_BLOG_ID", nullable = false)
	public int getBlogBlogId() {
		return this.blogBlogId;
	}

	public void setBlogBlogId(int blogBlogId) {
		this.blogBlogId = blogBlogId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TagId))
			return false;
		TagId castOther = (TagId) other;

		return (this.getTagId() == castOther.getTagId()) && (this.getBlogBlogId() == castOther.getBlogBlogId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTagId();
		result = 37 * result + this.getBlogBlogId();
		return result;
	}

}
